.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "infer-explore" 1 "2017-10-18" "v0.13.0" "Infer Explore"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
.nf
infer\N'45'explore \N'45' explore the error traces in infer reports
.fi
.SH SYNOPSIS
.P
.nf
\fBinfer\fR \fBexplore\fR \fI[options]\fR
.fi
.SH DESCRIPTION
.P
Show the list of bugs on the console and explore symbolic program traces emitted by infer to explain a report\N'46' Can also generate an HTML report from a JSON report\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR
Show this manual
.TP 4
\fB\N'45'\N'45'help\N'45'format\fR \fI{ auto | groff | pager | plain }\fR
Show this help in the specified format\N'46' \fBauto\fR sets the format to \fBplain\fR if the environment variable \fBTERM\fR is "dumb" or undefined, and to \fBpager\fR otherwise\N'46' (default: \fIauto\fR)
.TP 4
\fB\N'45'\N'45'help\N'45'full\fR
Show this manual with all internal options in the INTERNAL OPTIONS section
.TP 4
\fB\N'45'\N'45'html\fR
Activates: Generate html report\N'46' (Conversely: \fB\N'45'\N'45'no\N'45'html\fR)
.TP 4
\fB\N'45'\N'45'max\N'45'nesting\fR \fIint\fR
Level of nested procedure calls to show\N'46' Trace elements beyond the maximum nesting level are skipped\N'46' If omitted, all levels are shown\N'46'
.TP 4
\fB\N'45'\N'45'only\N'45'show\fR
Activates: Show the list of reports and exit (Conversely: \fB\N'45'\N'45'no\N'45'only\N'45'show\fR)
.TP 4
\fB\N'45'\N'45'results\N'45'dir\fR,\fB\N'45'o\fR \fIdir\fR
Write results and internal files in the specified directory (default: \fI/home/weimer/src/infer\N'45'linux64\N'45'v0\N'46'13\N'46'0/infer\N'45'out\fR)
.TP 4
\fB\N'45'\N'45'select\fR \fIN\fR
Select bug number \fIN\fR\N'46' If omitted, prompt for input\N'46'
.TP 4
\fB\N'45'\N'45'no\N'45'source\N'45'preview\fR
Deactivates: print code excerpts around trace elements (Conversely: \fB\N'45'\N'45'source\N'45'preview\fR)
.SH ENVIRONMENT
.TP 4
\fBINFER_ARGS\fR, \fBINFERCONFIG\fR, \fBINFER_STRICT_MODE\fR
See the ENVIRONMENT section in the manual of \fBinfer\fR(1)\N'46'
.SH FILES
.TP 4
\fB\N'46'inferconfig\fR
See the FILES section in the manual of \fBinfer\fR(1)\N'46'
.SH SEE ALSO
.P
\fBinfer\N'45'report\fR(1), \fBinfer\N'45'run\fR(1)